name: pgtk_pub_sub
description: A command-line application to build logical replication.
version: 0.1.0
repository: https://github.com/bigdino2/pgtk-pub-sub
publish_to: none

environment:
  sdk: ^3.7.3

dependencies:
  args: ^2.7.0
  copy_with_extension: ^6.0.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  pgtk_common:
    path: packages/pgtk_common

dev_dependencies:
  build_runner: ^2.4.15
  copy_with_extension_gen: ^6.0.1
  json_serializable: ^6.9.4
  test: ^1.24.0
  very_good_analysis: ^7.0.0
