name: pgtk_common
description: Common stuff for Postgres Toolkit command-line applications.
version: 0.1.0
repository: https://github.com/bigdino2/pgtk-common
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0
  copy_with_extension: ^6.0.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  logging: ^1.3.0
  postgres: ^3.5.5
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  copy_with_extension_gen: ^6.0.1
  json_serializable: ^6.9.4
  test: ^1.24.0
  very_good_analysis: ^7.0.0
